name: Build Flutter Debug APK (Android 9 / API 28)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Android SDK commandline tools and platform 28
        run: |
          echo "Installing Android commandline tools and platform 28..."
          mkdir -p "${ANDROID_SDK_ROOT}"
          cd "${ANDROID_SDK_ROOT}"
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
          unzip -q cmdline.zip -d cmdline-tools
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/ || true
          export PATH="$PATH:${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin"
          yes | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --licenses || true
          sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" "platform-tools" "platforms;android-28" "build-tools;33.0.2" "emulator" "system-images;android-28;google_apis;x86_64"
        shell: bash

      - name: Add Android SDK to PATH
        run: |
          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}" >> $GITHUB_ENV
          echo "${ANDROID_SDK_ROOT}/platform-tools" >> $GITHUB_PATH
          echo "${ANDROID_SDK_ROOT}/emulator" >> $GITHUB_PATH
          echo "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Flutter pub get
        run: flutter pub get

      - name: Ensure platform folders exist (flutter create)
        run: flutter create .

      - name: Build debug APK
        run: flutter build apk --debug --target-platform android-arm,android-arm64,android-x64

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk