name: Build Android APK and Flutter Web, deploy Web to GitHub Pages

# Grant the minimum write permissions required for the workflow to push to the repo and update Pages
permissions:
  contents: write   # required to push files/branches
  pages: write      # required for Pages API operations (if used)
  id-token: write   # sometimes needed for advanced auth; harmless to include

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-web:
    name: Build Web and Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # persist-credentials must be true so that git operations use the repo token
          persist-credentials: true

      - name: Download and install Flutter SDK (pinned)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Ensure pubspec has valid package name (optional check)
        run: |
          if grep -q "^name: .*[A-Z]" pubspec.yaml; then
            echo "Invalid package name found in pubspec.yaml (contains uppercase). Replacing with wealth_app_test."
            sed -i 's/^name: .*/name: wealth_app_test/' pubspec.yaml
            git --no-pager diff -- pubspec.yaml || true
          else
            echo "pubspec name OK."
          fi

      - name: Ensure platform folders exist (flutter create) with valid project name
        run: |
          # Force a correct android/ Gradle scaffold in CI
          flutter create . --project-name wealth_app_test --platforms web --overwrite

      - name: Enable web support
        run: flutter config --enable-web

      - name: Ensure web/ exists (create only if missing)
        run: |
          # If web/index.html is missing, add the web platform scaffolding.
          # This avoids overwriting any existing web/ files in your repo.
          if [ ! -f web/index.html ]; then
            flutter create --platforms=web .
            echo "web/ scaffolding created by flutter create"
          else
            echo "web/index.html already exists — skipping flutter create"
          fi

      - name: Get dependencies
        run: flutter pub get

      - name: flutter clean
        run: flutter clean

      - name: Build Flutter web
        run: flutter build web

      - name: Ensure relative base href in index.html
        run: |
          if ! grep -q '<base href="./">' build/web/index.html; then
            sed -i 's|<head>|<head>\n  <base href="./">|' build/web/index.html
            echo "Inserted base href"
          else
            echo "base href already present"
          fi

      - name: Prepare publish directory (SPA fallback + disable Jekyll)
        run: |
          cp build/web/index.html build/web/404.html || true
          touch build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build/web
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'chore: deploy Flutter web to GitHub Pages — ${{ github.sha }}'
