name: Build Android APK and Flutter Web, deploy Web to GitHub Pages

# Grant the minimum write permissions required for the workflow to push to the repo and update Pages
permissions:
  contents: write   # required to push files/branches
  pages: write      # required for Pages API operations (if used)
  id-token: write   # sometimes needed for advanced auth; harmless to include

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-web:
    name: Build Web and Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # persist-credentials must be true so that git operations use the repo token
          persist-credentials: true

      - name: Download and install Flutter SDK (pinned)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Ensure pubspec has valid package name (optional check)
        run: |
          if grep -q "^name: .*[A-Z]" pubspec.yaml; then
            echo "Invalid package name found in pubspec.yaml (contains uppercase). Replacing with wealth_app_test."
            sed -i 's/^name: .*/name: wealth_app_test/' pubspec.yaml
            git --no-pager diff -- pubspec.yaml || true
          else
            echo "pubspec name OK."
          fi

      # -------------------------
      # IMPORTANT CHANGE:
      # Do NOT run `flutter create . --overwrite` — that WILL overwrite lib/main.dart and other files.
      # If you need scaffolding for missing platforms, run `flutter create` WITHOUT --overwrite
      # or create only the missing platform. Below we ensure web platform exists but do NOT overwrite user code.
      # -------------------------
      - name: Ensure web platform scaffold exists (no overwrite)
        run: |
          # Create web scaffold only if missing (do NOT overwrite existing project files)
          if [ ! -d web ]; then
            echo "web/ missing — creating web platform scaffold"
            flutter create --platforms=web .
          else
            echo "web/ already exists — skipping flutter create"
          fi

      - name: Show current commit
        run: git log -1 --pretty=oneline

      - name: Show lib/main.dart (debug) so we know what will be compiled
        run: |
          echo "---- lib/main.dart (first 200 lines) ----"
          sed -n '1,200p' lib/main.dart || true
          echo "---- end ----"
          echo "git status:"
          git status --porcelain
          echo "git diff (if any):"
          git --no-pager diff -- lib/main.dart || true

      - name: Enable web support
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      - name: flutter clean
        run: flutter clean

      - name: Build Flutter web
        run: flutter build web --release --base-href "/wealth_app_test/"

      - name: debug build output
        run: |
          echo "build/web listing:"
          ls -lR build/web || true
          echo
          echo "main.dart.js md5 and head:"
          [ -f build/web/main.dart.js ] && { md5sum build/web/main.dart.js || true; head -c 512 build/web/main.dart.js | xxd | head -n 40 || true; } || echo "main.dart.js not found"

      - name: Ensure relative base href in index.html
        run: |
          if ! grep -q '<base href="./">' build/web/index.html; then
            sed -i 's|<head>|<head>\n  <base href="./">|' build/web/index.html
            echo "Inserted base href"
          else
            echo "base href already present"
          fi

      - name: Prepare publish directory (SPA fallback + disable Jekyll)
        run: |
          cp build/web/index.html build/web/404.html || true
          touch build/web/.nojekyll
          ls -ltr build/web/main.dart.js
          md5sum build/web/main.dart.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build/web
          exclude_assets: '.gitignore'
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'chore: deploy Flutter web to GitHub Pages — ${{ github.sha }}'
